// Writes N packed random-doubles teams (one per line) from deterministic seeds, for benchmarks and training.
//
// Usage: node tools/oracle/gen-teams.mjs <path-to-pokemon-showdown> --count N [--seed S] [--out <file>]
//
// Team j uses the Gen5 team-generator seed derived from SHA-256(`numbrion-oracle-v1/teams/<S>/<j>`)
// (see lib/common.mjs deriveTeamSeed), generated by Showdown's own gen9randomdoublesbattle generator
// and packed with Teams.pack. Without --out the teams are written to stdout.
import fs from 'node:fs';
import { FORMAT_ID, deriveTeamSeed, loadSim, seedString } from './lib/common.mjs';

const args = { psPath: null, count: 0, seed: 1, out: null };
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
	if (argv[i] === '--count') args.count = Number(argv[++i]);
	else if (argv[i] === '--seed') args.seed = Number(argv[++i]);
	else if (argv[i] === '--out') args.out = argv[++i];
	else if (!args.psPath) args.psPath = argv[i];
	else throw new Error(`unexpected argument ${argv[i]}`);
}
if (!args.psPath || !(args.count > 0)) {
	throw new Error('usage: gen-teams.mjs <path-to-pokemon-showdown> --count N [--seed S] [--out <file>]');
}

const { Teams } = loadSim(args.psPath);
const lines = [];
for (let j = 0; j < args.count; j++) {
	const generator = Teams.getGenerator(FORMAT_ID, seedString(deriveTeamSeed(args.seed, j)));
	lines.push(Teams.pack(generator.getTeam()));
}
const text = lines.join('\n') + '\n';
if (args.out) fs.writeFileSync(args.out, text);
else process.stdout.write(text);
