// Emits Rust test vectors for crates/engine/src/prng.rs from the pinned Showdown PRNG.
// Usage: node tools/oracle/prng-vectors.mjs <path-to-pokemon-showdown> > crates/engine/src/prng_vectors.rs
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(path.resolve(process.argv[2], 'package.json'));
const { PRNG } = require('./dist/sim/prng');

let p = new PRNG([1, 2, 3, 4]);
const next = Array.from({ length: 6 }, () => p.rng.next());
const seedAfter = p.getSeed().split(',').map(Number);
p = new PRNG([1, 2, 3, 4]);
const randomN = Array.from({ length: 6 }, (_, i) => p.random(16 + i));
p = new PRNG([9, 8, 7, 6]);
const shuffled = Array.from({ length: 10 }, (_, i) => i);
p.shuffle(shuffled);

console.log(`// GENERATED by tools/oracle/prng-vectors.mjs. Do not edit.
const EXPECTED_NEXT: [u32; 6] = [${next.join(', ')}];
const EXPECTED_SEED_AFTER_6: [u16; 4] = [${seedAfter.join(', ')}];
const EXPECTED_RANDOM_N: [u32; 6] = [${randomN.join(', ')}];
const EXPECTED_SHUFFLE: [u32; 10] = [${shuffled.join(', ')}];`);
