//! Effect-file authoring contract, battle.ts:641-646,845-859 and direct call sites.
//! Metadata construction makes no PRNG draws; a Hook body documents its own draws.
pub use crate::event::HookCtx;
use crate::{dex::HookId, ids::EffectId};
/// Monomorphized function bodies cannot be stored behind a generic fn pointer.
/// EffectImpl is registration metadata; build.rs generates static dispatch calls.
#[derive(Clone, Copy, Debug)]
pub struct EffectImpl {
    /// Canonical source path generated by build.rs; used to audit filename/id ownership.
    pub file: &'static str,
    pub id: EffectId,
    pub hooks: &'static [HookId],
    pub payload_words: usize,
    pub waivers: &'static [HookWaiver],
}
/// Numeric identity of the exact generated function site (including nested objects).
pub type Hook = HookId;
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WaiverReason {
    ValidationOnly,
    OutsideFormat,
}
/// Reached waived functions still panic; this is a coverage annotation, never a no-op.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HookWaiver {
    pub hook: HookId,
    pub reason: WaiverReason,
    pub explanation: &'static str,
}

/// Central temporary acknowledgement that a stage has not ported every effect.
/// This does not establish unreachability or permit a runtime no-op.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PendingPortWaiver {
    pub stage: &'static str,
    pub explanation: &'static str,
    pub plan: &'static str,
}

/// A disposition for every generated manifest site, including data-only sites.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum HookCoverage {
    Implemented,
    Waived(HookWaiver),
    Pending(PendingPortWaiver),
    Constant(crate::dex::DataValue),
    MetadataOnly,
}

/// Whole-manifest accounting. Pending functions make the registry incomplete.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ManifestCoverage {
    pub registered_effects: usize,
    pub functions: usize,
    pub implemented_functions: usize,
    pub waived_functions: usize,
    pub pending_functions: usize,
    pub constants: usize,
    pub metadata_only: usize,
}
impl ManifestCoverage {
    pub const fn complete(self) -> bool {
        self.pending_functions == 0
    }
}

/// Boundary-only diagnostic; never allocated in a battle callback.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RegistryAuditError(pub String);
impl core::fmt::Display for RegistryAuditError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(&self.0)
    }
}
impl std::error::Error for RegistryAuditError {}
