//! Independent full-battle protocol and PRNG expectations generated by the pinned oracle.
use crate::effects::registry::abilities_protosynthesis::tests::support::{
    check_scenario_teams, replay_scenario,
};
#[test]
fn batch_scenario_teams_are_scoped() {
    check_scenario_teams(include_str!("recursive_switch.tsv"));
    check_scenario_teams(include_str!("item_exchange.tsv"));
}
macro_rules! recursive { ($($name:ident),* $(,)?) => { $(
    #[test]
    fn $name() { replay_scenario(include_str!("recursive_switch.tsv"),stringify!($name)); }
)* }; }
macro_rules! item { ($($name:ident),* $(,)?) => { $(
    #[test]
    fn $name() { replay_scenario(include_str!("item_exchange.tsv"),stringify!($name)); }
)* }; }
recursive!(
    substitute_status_and_restart,
    substitute_break_and_recoil,
    substitute_drain,
    substitute_weak,
    batonpass_transfer,
    batonpass_no_bench,
    shedtail_transfer,
    shedtail_weak,
    magicbounce_status,
    magicbounce_side_once,
    magicbounce_partingshot,
    instruct_repeat_target,
    instruct_missing_lastmove,
    revival_no_fainted,
    revival_success
);
item!(
    trick_swap,
    trick_give_only,
    trick_take_only,
    trick_stickyhold,
    trick_empty_failure,
    knockoff_remove,
    knockoff_stickyhold,
    magician_take,
    magician_spread_tie,
    pickpocket_contact,
    pickpocket_no_contact,
    frisk_both_slots,
    poltergeist_success,
    poltergeist_empty_failure,
    recycle_no_lastitem
);

#[test]
fn item_callback_branches_match_pinned_oracle() {
    use crate::{Battle, actions::*, dex, event::*, ids::*, log::TextLog};
    fn id(s: &str) -> EffectId {
        if s.is_empty() {
            EffectId::NONE
        } else {
            dex::lookup(EffectKind::Item, s).unwrap()
        }
    }
    fn key(i: EffectId) -> &'static str {
        if i == EffectId::NONE {
            ""
        } else {
            dex::effect(i).key
        }
    }
    for row in include_str!("callbacks.tsv")
        .lines()
        .filter(|s| !s.starts_with('#'))
    {
        let c: Vec<_> = row.split('\t').collect();
        let packed = "Mew|||earlybird|irondefense|Serious||N|||100|,,,,,Normal";
        let team = format!("{packed}]{packed}");
        let mut b = Battle::from_players(
            [777, 888, 999, 111],
            ("Alice", &team),
            ("Bob", &team),
            TextLog::default(),
        )
        .unwrap();
        b.start().unwrap();
        let s = MonId(0);
        let t = if c[1] == "recycle" { s } else { MonId(6) };
        b.state.pokemon[t.0 as usize].item = id(c[2]);
        b.state.pokemon[s.0 as usize].item = id(c[3]);
        b.state.pokemon[t.0 as usize].ability = dex::lookup(EffectKind::Ability, c[4]).unwrap();
        b.state.pokemon[s.0 as usize].last_item = id(c[6]);
        if c[5] == "true" {
            b.state.pokemon[s.0 as usize].hp = 0;
        }
        let h = b.get_active_move(MoveInput::Dex(dex::lookup(EffectKind::Move, c[1]).unwrap()));
        b.set_active_move(Some(h), Some(s), Some(t));
        let mut log = Vec::new();
        b.drain_log(&mut log);
        log.clear();
        let result = b.single_event(
            EventId::Hit,
            EffectRef::ActiveMove(h.0),
            None,
            EventArg::Holder(Holder::mon(t)),
            EventArg::Holder(Holder::mon(s)),
            EffectRef::ActiveMove(h.0),
            Relay::Undefined,
            None,
        );
        assert_eq!(
            result,
            match c[7] {
                "true" => Relay::Bool(true),
                "false" => Relay::Bool(false),
                _ => panic!("unsupported oracle relay"),
            },
            "{row}"
        );
        assert_eq!(key(b.state.pokemon[t.0 as usize].item), c[8], "{row}");
        assert_eq!(key(b.state.pokemon[s.0 as usize].item), c[9], "{row}");
        assert_eq!(key(b.state.pokemon[s.0 as usize].last_item), c[10], "{row}");
        let seed: Vec<u16> = c[11].split(',').map(|n| n.parse().unwrap()).collect();
        assert_eq!(b.seed(), seed.as_slice(), "{row}");
        b.drain_log(&mut log);
        let expected: Vec<_> = c[12].split("\\n").filter(|l| !l.is_empty()).collect();
        assert_eq!(log, expected, "{row}");
    }
}
