//! Tests for the reactive_stats batch. The helper tests and the scenario-table checks run
//! today; the full-battle replay awaits Protect in the protect_redirection batch.
//!
//! `scenarios.tsv` is generated by `tools/probes/reactive_stats/scenarios.mjs` from the pinned
//! Showdown build: each row holds two packed teams, the choices to apply, the expected raw
//! battle log and the final PRNG seed.
use super::*;
use crate::log::TextLog;

const SCENARIOS: &str = include_str!("scenarios.tsv");

struct Scenario<'a> {
    name: &'a str,
    seed: [u16; 4],
    teams: [&'a str; 2],
    steps: &'a str,
    final_seed: [u16; 4],
    log: &'a str,
}

fn seed(text: &str) -> [u16; 4] {
    let parts: Vec<u16> = text.split(',').map(|n| n.parse().unwrap()).collect();
    parts.try_into().unwrap()
}

fn scenarios() -> impl Iterator<Item = Scenario<'static>> {
    SCENARIOS
        .lines()
        .filter(|row| !row.starts_with('#'))
        .map(|row| {
            let c: Vec<&str> = row.split('\t').collect();
            assert_eq!(c.len(), 7, "malformed scenario row: {row}");
            Scenario {
                name: c[0],
                seed: seed(c[1]),
                teams: [c[2], c[3]],
                steps: c[4],
                final_seed: seed(c[5]),
                log: c[6],
            }
        })
}

#[test]
fn scenario_teams_load_without_touching_the_prng() {
    let mut count = 0;
    for s in scenarios() {
        // Every set names an explicit gender, so construction must not sample the PRNG.
        let battle = Battle::new(s.seed, s.teams[0], s.teams[1])
            .unwrap_or_else(|e| panic!("{}: {e:?}", s.name));
        assert_eq!(battle.seed(), s.seed, "{}", s.name);
        assert!(!s.log.is_empty() && s.log.contains("|start"), "{}", s.name);
        count += 1;
    }
    assert_eq!(count, 9);
}

#[test]
#[ignore = "pending protect_redirection: moves:protect onPrepareHit"]
fn scenario_logs_and_prng_match_pinned_showdown() {
    for s in scenarios() {
        let mut battle = Battle::from_players(
            s.seed,
            ("Alice", s.teams[0]),
            ("Bob", s.teams[1]),
            TextLog::default(),
        )
        .unwrap();
        battle.start().unwrap();
        for step in s.steps.split(';').filter(|step| !step.is_empty()) {
            let side = match &step[..2] {
                "p1" => 0,
                "p2" => 1,
                other => panic!("{}: bad side {other}", s.name),
            };
            battle
                .choose(side, &step[3..])
                .unwrap_or_else(|e| panic!("{}: {step}: {e}", s.name));
        }
        let mut log = Vec::new();
        battle.drain_log(&mut log);
        // Wall-clock `|t:|<secs>` lines are normalized exactly like the oracle fixtures.
        let log: Vec<String> = log
            .into_iter()
            .map(|l| {
                if l.starts_with("|t:|") {
                    "|t:|".to_owned()
                } else {
                    l
                }
            })
            .collect();
        let expected: Vec<&str> = s.log.split("\\n").collect();
        assert_eq!(log, expected, "{}: battle log", s.name);
        assert_eq!(battle.seed(), s.final_seed, "{}: final PRNG state", s.name);
    }
}

#[test]
fn type_constants_match_the_generated_type_table() {
    for (name, id) in [
        ("Bug", TYPE_BUG),
        ("Dark", TYPE_DARK),
        ("Fire", TYPE_FIRE),
        ("Ghost", TYPE_GHOST),
        ("Water", TYPE_WATER),
    ] {
        assert_eq!(Some(id), dex::type_id(name), "{name}");
    }
}

#[test]
fn boost_objects_keep_insertion_order_and_presence() {
    // Weak Armor: this.boost({ def: -1, spe: 2 }) applies def first, then spe.
    let b = boosts([(Stat::Def, -1), (Stat::Spe, 2)]);
    assert_eq!(b.len, 2);
    assert_eq!(&b.order[..2], &[1, 4]);
    assert_eq!(b.present, 0b1_0010);
    assert_eq!((b.values[1], b.values[4]), (-1, 2));
    // Same keys in the other order are a different object.
    let b = boosts([(Stat::Spe, 2), (Stat::Def, -1)]);
    assert_eq!(&b.order[..2], &[4, 1]);
    assert_eq!(boost_get(&b, Stat::Atk), None);
    assert_eq!(boost_get(&b, Stat::Spe), Some(2));
}

#[test]
fn lowered_detection_ignores_absent_keys() {
    assert!(any_lowered(&boosts([(Stat::Atk, -1)])));
    assert!(any_lowered(&boosts([(Stat::Atk, 1), (Stat::Def, -2)])));
    assert!(!any_lowered(&boosts([(Stat::Atk, 2)])));
    assert!(!any_lowered(&OrderedBoosts::default()));
}
