//! Lexical effect-file discovery; no dependencies and no Showdown checkout access.
use std::{env, fs, path::PathBuf};
fn main() {
    let root = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let mut files = Vec::new();
    for family in [
        "abilities",
        "conditions",
        "items",
        "moves",
        "rules",
        "species",
    ] {
        let dir = root.join("src/effects").join(family);
        println!("cargo:rerun-if-changed={}", dir.display());
        let mut entries: Vec<_> = fs::read_dir(&dir)
            .unwrap()
            .map(|e| e.unwrap().path())
            .collect();
        entries.sort();
        for path in entries {
            if path.extension().is_none_or(|x| x != "rs") {
                continue;
            }
            let key = path.file_stem().unwrap().to_str().unwrap();
            assert!(
                key != "mod"
                    && !key.is_empty()
                    && key
                        .bytes()
                        .all(|x| x.is_ascii_lowercase() || x.is_ascii_digit()),
                "effect files must be canonical lowercase alphanumeric IDs: {}",
                path.display()
            );
            files.push((format!("{family}_{key}"), path));
        }
    }
    let mut out = String::from("// GENERATED by engine/build.rs; do not edit.\n");
    for (name, path) in &files {
        out.push_str(&format!("#[path = {:?}] mod {name};\n", path));
    }
    out.push_str("pub static IMPLEMENTATIONS: &[crate::effects::EffectImpl] = &[\n");
    for (name, _) in &files {
        out.push_str(&format!("crate::effects::EffectImpl {{ id:{name}::ID, hooks:{name}::HOOKS, payload_words:{name}::PAYLOAD_WORDS, waivers:{name}::WAIVERS }},\n"));
    }
    out.push_str("];\n#[allow(unused_variables)]\npub fn dispatch_function<L: crate::log::LogSink>(hook:crate::dex::HookId,b:&mut crate::Battle<L>,cx:crate::event::HookCtx)->crate::event::Relay {\nlet id=crate::dex::HOOKS[hook.0 as usize].effect;\nmatch id {\n");
    for (name, _) in &files {
        out.push_str(&format!("{name}::ID => {name}::dispatch(hook,b,cx),\n"));
    }
    out.push_str("_ => { let h=&crate::dex::HOOKS[hook.0 as usize]; panic!(\"unimplemented effect hook: {} {} {}\",crate::dex::effect(id).key,h.key,h.site) }\n}\n}\n");
    fs::write(
        PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("effects_registry.rs"),
        out,
    )
    .unwrap();
}
