// GENERATED by tools/oracle/prng-vectors.mjs. Do not edit.
const EXPECTED_NEXT: [u32; 6] = [2030470262, 3793892072, 2851743046, 574702432, 3620926519, 2468984361];
const EXPECTED_SEED_AFTER_6: [u16; 4] = [37673, 46633, 62039, 8266];
const EXPECTED_RANDOM_N: [u32; 6] = [7, 15, 11, 2, 16, 12];
const EXPECTED_SHUFFLE: [u32; 10] = [2, 7, 9, 3, 5, 4, 6, 0, 8, 1];
