//! Tests for the text sink and protocol formatting (owner T).
//!
//! * `state`   - ident / details / health / full-details strings against the pinned Showdown
//!   (`state-vectors.tsv`, generated by `tools/probes/textlog/state-vectors.mjs`).
//! * `replay`  - real fixture logs translated back into structured entries, replayed through
//!   `Battle::add`/`add_move`/`attr_last_move`, compared byte for byte (`replay-vectors.tsv`,
//!   `tools/probes/textlog/extract-replay.mjs`).
//! * `shapes`  - one case per line shape of `docs/showdown/05-log-shapes.txt`.
//! * `moves`   - `addMove` / `attrLastMove` / `retargetLastMove` semantics.
//! * `counting`- drain cursor, logical unsent-line counting, hints, opening log, NoLog parity.
use super::*;
use crate::{
    Battle,
    dex,
    ids::*,
    log::{LogArg, LogEntry, LogTag, LogView, MoveLineEdit, NoLog},
    state::{Status, mon_flags, scratch::EffectRef},
};

mod counting;
mod moves;
mod replay;
mod shapes;
mod state;

pub(super) const STATE_VECTORS: &str = include_str!("state-vectors.tsv");

/// The two 6-mon teams and player names every state/shape test shares (first lines of the vectors).
pub(super) fn standard_teams() -> ([String; 2], [String; 2]) {
    let mut names = Vec::new();
    let mut teams = Vec::new();
    for line in STATE_VECTORS.lines() {
        if let Some(rest) = line.strip_prefix("#NAMES\t") {
            names = rest.split('\t').map(str::to_owned).collect();
        } else if let Some(rest) = line.strip_prefix("#TEAM\t") {
            teams.push(rest.to_owned());
        }
    }
    (
        [names[0].clone(), names[1].clone()],
        [teams[0].clone(), teams[1].clone()],
    )
}

pub(super) fn standard() -> Battle<TextLog> {
    let (names, teams) = standard_teams();
    Battle::from_players(
        [1, 2, 3, 4],
        (&names[0], &teams[0]),
        (&names[1], &teams[1]),
        TextLog::default(),
    )
    .expect("standard teams")
}

/// `p1:0` style reference (0-based side and party index) to a MonId.
pub(super) fn mon(side: u8, index: u8) -> MonId {
    MonId(side * 6 + index)
}

/// Mirrors a switch-in: the mon becomes active in field slot `slot` (0 = a, 1 = b).
pub(super) fn activate(b: &mut Battle<TextLog>, m: MonId, slot: u8) {
    let side = m.side().0 as usize;
    let old = b.state.sides[side].active[slot as usize];
    if old != MonId::NONE {
        b.state.pokemon[old.0 as usize].flags &= !mon_flags::ACTIVE;
    }
    b.state.sides[side].active[slot as usize] = m;
    let p = &mut b.state.pokemon[m.0 as usize];
    p.flags |= mon_flags::ACTIVE;
    p.position = slot;
}

/// Standard battle with p1a Wugtrio, p1b Dondozo, p2a Klefki, p2b Reshiram on the field.
pub(super) fn standard_active() -> Battle<TextLog> {
    let mut b = standard();
    for (m, slot) in [(0, 0), (1, 1)] {
        activate(&mut b, mon(0, m), slot);
    }
    for (m, slot) in [(0, 0), (1, 1)] {
        activate(&mut b, mon(1, m), slot);
    }
    b
}

pub(super) fn lines(b: &Battle<TextLog>) -> Vec<&str> {
    b.log.entries.iter().map(String::as_str).collect()
}

pub(super) fn last(b: &Battle<TextLog>) -> &str {
    b.log.entries.last().expect("a log entry")
}

/// Emit a plain entry and return the entries it produced.
pub(super) fn add(
    b: &mut Battle<TextLog>,
    command: &'static str,
    args: &[LogArg<'_>],
    tags: &[LogTag<'_>],
) -> Vec<String> {
    let before = b.log.entries.len();
    b.add(LogEntry::new(command, args, tags));
    b.log.entries[before..].to_vec()
}

/// Emit a split entry and return the three entries.
pub(super) fn add_split(
    b: &mut Battle<TextLog>,
    command: &'static str,
    args: &[LogArg<'_>],
    tags: &[LogTag<'_>],
    side: u8,
    secret_only: bool,
) -> Vec<String> {
    let before = b.log.entries.len();
    b.add(LogEntry::split(command, args, tags, SideId(side), secret_only));
    b.log.entries[before..].to_vec()
}

pub(super) fn id(kind: EffectKind, name: &str) -> EffectId {
    dex::lookup(kind, name).unwrap_or_else(|| panic!("unknown {kind:?} {name}"))
}

pub(super) fn fx(kind: EffectKind, name: &str) -> EffectRef {
    EffectRef::Dex(id(kind, name))
}

pub(super) fn view(b: &Battle<TextLog>) -> LogView<'_> {
    LogView {
        state: &b.state,
        teams: &b.teams,
        player_names: &b.names,
        moves: &b.scratch.moves,
    }
}

pub(super) fn status_of(s: &str) -> Status {
    match s {
        "" => Status::None,
        "brn" => Status::Burn,
        "par" => Status::Paralysis,
        "slp" => Status::Sleep,
        "frz" => Status::Freeze,
        "psn" => Status::Poison,
        "tox" => Status::Toxic,
        "fnt" => Status::Fainted,
        other => panic!("status {other}"),
    }
}
