const ps=process.argv[2]||'/home/aminaliu/src/pokemon-showdown';const {Battle}=require(ps+'/dist/sim');
const packed='Pikachu||choicescarf|static|thunderbolt,uturn|Serious||M|||100|,,,,,Electric';
function fixture(){const b=new Battle({formatid:'gen9randomdoublesbattle',seed:[1,2,3,4]});b.start=()=>{};b.setPlayer('p1',{team:packed+']'+packed});b.setPlayer('p2',{team:packed+']'+packed});b.p1.foe=b.p2;b.p2.foe=b.p1;const p=b.p1.pokemon[0],t=b.p2.pokemon[0];b.p1.active=b.p1.pokemon.slice();b.p2.active=b.p2.pokemon.slice();for(const m of [...b.p1.active,...b.p2.active])m.isActive=true;b.field.pseudoWeather={};b.log=[];return {b,p,t};}
const ret=r=>r&&typeof r==='object'?r.id:String(r);
function row(op,key,f,r){const {b,p}=f;console.log([op,key,ret(r),p.species.id,p.baseSpecies.id,p.hp,p.maxhp,Object.values(p.storedStats).join(','),Object.values(p.baseStoredStats).filter((_,i)=>i>0).join(','),p.types.join(','),p.apparentType,p.addedType||'-',Number(p.knownType),Number(p.transformed),p.ability,p.baseAbility,p.weighthg,p.speed,b.effectOrder,b.prng.getSeed(),p.moveSlots.map(m=>[m.id,m.pp,m.maxpp,Number(m.used),String(m.disabled),m.disabledSource||'-'].join(':')).join(','),p.baseMoveSlots.map(m=>m.pp).join(','),b.log.filter(x=>!x.startsWith('|split|')).map(x=>x.split('|')[1]).join(',')||'-'].join('\t'));}
for(const species of ['charizard','rotomheat','darmanitanzen','mimikyubusted'])for(const permanent of [false,true]){const f=fixture();f.p.hp-=50;row('forme',species+':'+Number(permanent),f,f.p.formeChange(species,f.b.dex.abilities.get('static'),permanent));}
for(const species of ['charizard','rotomheat']){const f=fixture();row('species',species,f,f.p.setSpecies(f.b.dex.species.get(species)));}
{const f=fixture();f.t.setSpecies(f.b.dex.species.get('charizard'));f.t.storedStats.atk=234;f.t.boosts.atk=3;f.t.timesAttacked=7;row('transform','charizard',f,f.p.transformInto(f.t,f.b.dex.moves.get('transform')));f.p.deductPP('thunderbolt',2);row('transformpp','-',f,true);f.p.clearVolatile();row('clearvolatile','-',f,true);}
for(const hidden of [false,true]){const f=fixture();f.p.disableMove('thunderbolt',hidden,f.b.dex.conditions.get('confusion'));row('disable',String(Number(hidden)),f,true);f.p.deductPP('thunderbolt',999);row('pp',String(Number(hidden)),f,true);}
for(const types of [['Water'],['Fire','Flying']]){const f=fixture();row('type',types.join(','),f,f.p.setType(types));row('addtype','Ghost',f,f.p.addType('Ghost'));}
for(const tera of ['Electric','Stellar']){const f=fixture();f.p.terastallized=tera;row('teratype',tera,f,f.p.setType('Water'));}
{const f=fixture();f.p.addVolatile('confusion');f.p.boosts.atk=4;const recv=f.b.p1.pokemon[1];recv.copyVolatileFrom(f.p);f.p=recv;row('copy','confusion',f,true);}
for(const status of ['brn','confusion'])for(const kind of ['side','slot','weather','terrain','pseudo']){const f=fixture();const r=kind==='side'?f.p.side.addSideCondition(status,f.p):kind==='slot'?f.p.side.addSlotCondition(0,status,f.p):kind==='weather'?f.b.field.setWeather(status,f.p):kind==='terrain'?f.b.field.setTerrain(status,f.p):f.b.field.addPseudoWeather(status,f.p);row(kind,status,f,r);}

{const f=fixture();f.t.ability='hugepower';row('skillswap','hugepower',f,f.b.skillSwap(f.p,f.t));}
