// Ground truth for the mutable move line: random sequences of the real pinned-Showdown
// `Battle.add` / `addMove` / `attrLastMove` / `retargetLastMove` calls and the resulting
// `battle.log`. crates/engine/src/log/text/tests/edits.rs replays every sequence through
// Battle::add / add_move / attr_last_move and compares the whole log.
//
//   node tools/probes/textlog/edit-vectors.mjs [<showdown checkout>] > \
//        crates/engine/src/log/text/tests/edit-vectors.tsv
//
// Row: ops <TAB> expected log. Ops are separated by U+001E, op fields by U+001F, log entries by U+001E.
//   plain  cmd arg...             battle.add(cmd, arg...)
//   move   user name target [from]  addMove('move', user, name, `${target}${attrs}`)  (attrs = `|[from] ${from}`)
//   bare   user name              addMove('move', user, name)   (choice-lock / Gorilla Tactics fail paths)
//   anim   user name target       addMove('-anim', user, name, target)
//   attr   tag                    attrLastMove(tag)
//   retarget ident                retargetLastMove({toString: () => ident})
import { loadSim } from '../../oracle/lib/common.mjs';

const sim = loadSim(process.argv[2] || '/home/aminaliu/src/pokemon-showdown');
const battle = new sim.Battle({ formatid: 'gen9randomdoublesbattle', seed: '1,2,3,4' });

const ACTIVE = ['p1a: Wugtrio', 'p1b: Dondozo', 'p2a: Klefki', 'p2b: Reshiram'];
const TARGETS = [...ACTIVE, 'p1: Gholdengo', 'p2: Basculegion'];
const MOVES = ['Protect', 'Icy Wind', 'Earthquake', 'Life Dew', 'Meteor Beam', 'Thunder Wave', 'Stealth Rock'];
const FROM = ['lockedmove', 'ability: Dancer', 'ability: Magic Bounce'];
const ATTRS = ['[still]', '[still]', '[miss]', '[notarget]', '[spread] ', '[spread] p2a', '[spread] p2a,p2b', '[spread] p2b,p1a,p1b',
	'[anim] Tera Blast Ground', '[from] ability: Dancer'];
const PLAIN = [['-fail', 'p1a: Wugtrio'], ['-damage', 'p2a: Klefki', '27/217'], ['turn', '3'], [''], ['', ''], ['-supereffective', 'p2b: Reshiram'], ['upkeep']];

let state = 12345;
const rnd = (n) => { state = (state * 1103515245 + 12345) & 0x7fffffff; return (state >> 8) % n; };
const pick = (a) => a[rnd(a.length)];

function genOps() {
	const ops = [];
	const n = 2 + rnd(9);
	for (let i = 0; i < n; i++) {
		const r = rnd(20);
		if (r < 5) ops.push(['move', pick(ACTIVE), pick(MOVES), pick(TARGETS), ...(rnd(3) === 0 ? [pick(FROM)] : [])]);
		else if (r < 6) ops.push(['bare', pick(ACTIVE), pick(MOVES)]);
		else if (r < 8) ops.push(['anim', pick(ACTIVE), pick(MOVES), pick(TARGETS)]);
		else if (r < 14) ops.push(['attr', pick(ATTRS)]);
		else if (r < 16) ops.push(['retarget', pick(TARGETS)]);
		else ops.push(['plain', ...pick(PLAIN)]);
	}
	return ops;
}

function run(ops) {
	battle.log = [];
	battle.lastMoveLine = -1;
	for (const [op, ...a] of ops) {
		if (op === 'plain') battle.add(...a);
		else if (op === 'move') battle.addMove('move', a[0], a[1], `${a[2]}${a[3] ? `|[from] ${a[3]}` : ''}`);
		else if (op === 'bare') battle.addMove('move', a[0], a[1]);
		else if (op === 'anim') battle.addMove('-anim', a[0], a[1], a[2]);
		else if (op === 'attr') battle.attrLastMove(a[0]);
		else if (op === 'retarget') battle.retargetLastMove({ toString: () => a[0] });
		else throw new Error(op);
	}
	return battle.log.slice();
}

let out = '# generated by tools/probes/textlog/edit-vectors.mjs from the pinned Showdown; do not edit\n';
let rows = 0;
for (let i = 0; i < 600; i++) {
	const ops = genOps();
	const log = run(ops);
	out += ops.map(o => o.join('\u001f')).join('\u001e') + '\t' + log.join('\u001e') + '\n';
	rows++;
}
process.stdout.write(out);
process.stderr.write(`${rows} sequences\n`);
