//! Tests for the `consumables` batch.
//!
//! `scenarios.tsv` is generated by `tools/probes/consumables/scenarios.mjs` from the pinned
//! Showdown build: each row holds two packed teams, the choices to apply, the expected raw
//! battle log and the final PRNG seed. The scenarios cover Sitrus/Chesto/Figy/Aguav/Iapapa/
//! Mago/Wiki Berry (incl. Gluttony and the minus-stat confusion), Focus Sash, Weakness Policy,
//! Throat Spray, White Herb, Cheek Pouch, Ripen, Harvest (sun and random) and Unnerve.
use super::*;
use crate::log::TextLog;

const SCENARIOS: &str = include_str!("scenarios.tsv");

/// Scenarios whose expected log needs a core fix (event collection must skip Ally/Foe/Any
/// listeners of Pokemon with hp 0 that are not yet marked fainted, side.ts:390-403); they are
/// replayed by the `#[ignore]`d test below.
const CORE_BLOCKED: &[&str] = &["unnerve_holder_ko_frees_berry"];

struct Scenario<'a> {
    name: &'a str,
    seed: [u16; 4],
    teams: [&'a str; 2],
    steps: &'a str,
    final_seed: [u16; 4],
    log: &'a str,
}

fn seed(text: &str) -> [u16; 4] {
    let parts: Vec<u16> = text.split(',').map(|n| n.parse().unwrap()).collect();
    parts.try_into().unwrap()
}

fn scenarios() -> impl Iterator<Item = Scenario<'static>> {
    SCENARIOS
        .lines()
        .filter(|row| !row.starts_with('#'))
        .map(|row| {
            let c: Vec<&str> = row.split('\t').collect();
            assert_eq!(c.len(), 7, "malformed scenario row: {row}");
            Scenario {
                name: c[0],
                seed: seed(c[1]),
                teams: [c[2], c[3]],
                steps: c[4],
                final_seed: seed(c[5]),
                log: c[6],
            }
        })
}

fn replay(s: &Scenario<'_>) -> (Vec<String>, [u16; 4]) {
    let mut battle = Battle::from_players(
        s.seed,
        ("Alice", s.teams[0]),
        ("Bob", s.teams[1]),
        TextLog::default(),
    )
    .unwrap_or_else(|e| panic!("{}: {e:?}", s.name));
    battle.start().unwrap();
    for step in s.steps.split(';').filter(|step| !step.is_empty()) {
        let side = match &step[..2] {
            "p1" => 0,
            "p2" => 1,
            other => panic!("{}: bad side {other}", s.name),
        };
        battle
            .choose(side, &step[3..])
            .unwrap_or_else(|e| panic!("{}: {step}: {e}", s.name));
    }
    let mut log = Vec::new();
    battle.drain_log(&mut log);
    // Wall-clock `|t:|<secs>` lines are normalized exactly like the oracle fixtures.
    let log = log
        .into_iter()
        .map(|l| {
            if l.starts_with("|t:|") {
                "|t:|".to_owned()
            } else {
                l
            }
        })
        .collect();
    (log, battle.seed())
}

#[test]
fn scenario_teams_load_without_touching_the_prng() {
    let mut count = 0;
    for s in scenarios() {
        // Every set names an explicit gender, so construction must not sample the PRNG.
        let battle = Battle::new(s.seed, s.teams[0], s.teams[1])
            .unwrap_or_else(|e| panic!("{}: {e:?}", s.name));
        assert_eq!(battle.seed(), s.seed, "{}", s.name);
        assert!(!s.log.is_empty() && s.log.contains("|start"), "{}", s.name);
        count += 1;
    }
    assert_eq!(count, 16);
}

fn check_scenarios(blocked: bool) {
    let mut count = 0;
    for s in scenarios().filter(|s| CORE_BLOCKED.contains(&s.name) == blocked) {
        let (log, final_seed) = replay(&s);
        let expected: Vec<&str> = s.log.split("\\n").collect();
        assert_eq!(log, expected, "{}: battle log", s.name);
        assert_eq!(final_seed, s.final_seed, "{}: final PRNG state", s.name);
        count += 1;
    }
    assert!(count > 0);
}

#[test]
fn scenario_logs_and_prng_match_pinned_showdown() {
    check_scenarios(false);
}

/// Unnerve holder knocked out by a hit: the foe's berry must be eaten at the Update that runs
/// before `|faint|`. Passes once `event/collect.rs` skips hp 0 actives for Ally/Foe/Any handlers.
#[test]
#[ignore = "needs core: Foe/Ally/Any listener collection must skip hp 0 actives (side.ts:393-403)"]
fn scenarios_blocked_on_core_event_collection() {
    check_scenarios(true);
}

#[test]
fn state_flag_bits_are_distinct_custom_bits() {
    for flag in [
        GLUTTONY_FLAG,
        BERRY_WEAKEN_FLAG,
        UNNERVED_FLAG,
        HERB_BOOSTS_PRESENT,
    ] {
        assert_eq!(flag, 1 << 8);
        assert_eq!(
            flag & ((1 << 8) - 1),
            0,
            "must not collide with common bits"
        );
    }
}

#[test]
fn nature_constants_match_the_generated_nature_table() {
    let find = |key: &str| dex::NATURES.iter().find(|n| n.key == key).unwrap();
    // minus stat: Modest -atk, Bold -atk, Naughty -spd, Lonely -def, Brave -spe, Adamant -spa.
    assert_eq!(find("modest").minus, NATURE_ATK);
    assert_eq!(find("naughty").minus, NATURE_SPD);
    assert_eq!(find("lonely").minus, NATURE_DEF);
    assert_eq!(find("brave").minus, NATURE_SPE);
    assert_eq!(find("adamant").minus, NATURE_SPA);
    // Neutral natures have no minus stat and so never equal one of the stat keys.
    for key in ["hardy", "docile", "serious", "bashful", "quirky"] {
        assert_eq!(find(key).minus, -1, "{key}");
        assert_eq!(find(key).plus, -1, "{key}");
    }
}

#[test]
fn berry_table_matches_the_scoped_item_flags() {
    for (id, berry) in [
        (dex::ITEM_SITRUSBERRY, true),
        (dex::ITEM_AGUAVBERRY, true),
        (dex::ITEM_FIGYBERRY, true),
        (dex::ITEM_IAPAPABERRY, true),
        (dex::ITEM_MAGOBERRY, true),
        (dex::ITEM_WIKIBERRY, true),
        (dex::ITEM_CHESTOBERRY, true),
        (dex::ITEM_FOCUSSASH, false),
        (dex::ITEM_LEFTOVERS, false),
        (dex::ITEM_WHITEHERB, false),
    ] {
        assert_eq!(item_is_berry(id), berry, "{id:?}");
    }
    // Absent items and non-item ids are never berries.
    assert!(!item_is_berry(EffectId::NONE));
    assert!(!item_is_berry(dex::ABILITY_RIPEN));
    // A name missing from the scoped dex resolves to NONE and must never match anything.
    assert_eq!(item_named("berryjuice"), EffectId::NONE);
    assert!(!is_named(EffectId::NONE, item_named("berryjuice")));
    assert!(!is_listed(EffectId::NONE, &[EffectId::NONE]));
    assert!(is_named(dex::ITEM_LEFTOVERS, item_named("leftovers")));
    assert!(is_listed(
        dex::ITEM_SITRUSBERRY,
        &[dex::ITEM_AGUAVBERRY, dex::ITEM_SITRUSBERRY]
    ));
}

#[test]
fn white_herb_boost_tables_keep_ascending_key_order() {
    let boosts = zeroed_boosts(0b101_0010);
    // keys def (1), spe (4)... bit 1, bit 4 and bit 6 -> def, spe, evasion in that order.
    assert_eq!(boosts.len, 3);
    assert_eq!(&boosts.order[..3], &[1, 4, 6]);
    assert_eq!(boosts.present, 0b101_0010);
    assert!(boosts.values.iter().all(|v| *v == 0));
    let empty = zeroed_boosts(0);
    assert_eq!((empty.len, empty.present), (0, 0));
}
